export type StockChartPoint = { time: string; price: number };
export type StockAnalystTargets = {
  low: number | null;
  mean: number | null;
  median: number | null;
  high: number | null;
  upside_pct: number | null;
};
export type StockRecommendations = {
  strong_buy: number;
  buy: number;
  hold: number;
  sell: number;
  strong_sell: number;
  consensus: string;
  num_analysts: number;
};
export type StockEarningsCalendar = {
  earnings_date: string | null;
  eps_estimate_low: number | null;
  eps_estimate_high: number | null;
  eps_estimate_avg: number | null;
  revenue_estimate_low: number | null;
  revenue_estimate_high: number | null;
  revenue_estimate_avg: number | null;
  dividend_date: string | null;
  ex_dividend_date: string | null;
};
export type StockAnalysisProps = {
  symbol: string;
  name: string;
  exchange: string | null;
  currency: string | null;
  sector: string | null;
  industry: string | null;
  country: string | null;
  website: string | null;
  employees: number | null;
  description: string | null;
  price: number | null;
  previous_close: number | null;
  change: number | null;
  change_percent: number | null;
  open: number | null;
  day_high: number | null;
  day_low: number | null;
  volume: number | null;
  avg_volume: number | null;
  market_cap: number | null;
  enterprise_value: number | null;
  fifty_two_week_high: number | null;
  fifty_two_week_low: number | null;
  fifty_day_avg: number | null;
  two_hundred_day_avg: number | null;
  fifty_two_week_position_pct: number | null;
  trailing_pe: number | null;
  forward_pe: number | null;
  peg_ratio: number | null;
  price_to_book: number | null;
  price_to_sales: number | null;
  eps_trailing: number | null;
  eps_forward: number | null;
  dividend_rate: number | null;
  dividend_yield: number | null;
  payout_ratio: number | null;
  earnings_growth: number | null;
  revenue_growth: number | null;
  earnings_quarterly_growth: number | null;
  gross_margin: number | null;
  operating_margin: number | null;
  profit_margin: number | null;
  return_on_equity: number | null;
  return_on_assets: number | null;
  total_cash: number | null;
  total_debt: number | null;
  debt_to_equity: number | null;
  current_ratio: number | null;
  free_cashflow: number | null;
  operating_cashflow: number | null;
  short_ratio: number | null;
  short_percent_of_float: number | null;
  beta: number | null;
  analyst_targets: StockAnalystTargets;
  recommendations: StockRecommendations;
  calendar: StockEarningsCalendar;
  financials: StockFinancials;
  sparkline_1mo: StockChartPoint[];
  intraday: StockChartPoint[];
  summary: string;
  error: string | null;
};

export type StockFinancialPeriod = {
  period: string;
  revenue: number | null;
  gross_profit: number | null;
  operating_income: number | null;
  net_income: number | null;
  ebitda: number | null;
  eps: number | null;
  rd: number | null;
  total_debt: number | null;
  stockholders_equity: number | null;
  total_assets: number | null;
  current_assets: number | null;
  current_liabilities: number | null;
  cash: number | null;
  free_cashflow: number | null;
  operating_cashflow: number | null;
  capex: number | null;
  buybacks: number | null;
};

export type StockFinancials = {
  annual: StockFinancialPeriod[];
  quarterly: StockFinancialPeriod[];
};

export type FinancialMetric = Exclude<keyof StockFinancialPeriod, "period">;
